# spring配置
spring:
  redis:
    host: localhost
    port: 6379
    password:
  datasource:
    dynamic:
      datasource:
        master:
          username: root
          password: 123456
          url: jdbc:mysql://localhost:3306/ry-cloud?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          driver-class-name: com.mysql.cj.jdbc.Driver
        order:
          username: root
          password: 123456
          url: jdbc:mysql://localhost:3306/ry-order?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev

server:
  port: 9201
  servlet:
    context-path: /

logging:
  level:
    com.phoenix: debug
    org.springframework: warn

# mybatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.phoenix.shardingsphere.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath:mapper/**/*.xml
